api_book:
    resource: "@ApiBundle/Controller/BookController.php"
    type:     rest
    prefix:   /api/book

api_author:
    resource: "@ApiBundle/Controller/AuthorController.php"
    type:     rest
    prefix:   /api/author

app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
