api_book:
    resource: "@ApiBundle/Controller/BookController.php"
    type:     rest
    prefix:   /api/book

api_author:
    resource: "@ApiBundle/Controller/AuthorController.php"
    type:     rest
    prefix:   /api/author

api_publisher:
    resource: "@ApiBundle/Controller/PublisherController.php"
    type:     rest
    prefix:   /api/publisher

app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_search:
    path:     /search
    defaults: { _controller: AppBundle:Default:search }

app_login:
    path:     /login
    defaults: { _controller: AppBundle:Security:index }

login_checker_type:
    path:     /login/check
    defaults: { _controller: AppBundle:Security:check }

admin_homepage:
    path:     /admin
    defaults: { _controller: AppBundle:Admin:index }

admin_books:
    path:     /admin/books
    defaults: { _controller: AppBundle:Admin:books }

admin_publishers:
    path:     /admin/publishers
    defaults: { _controller: AppBundle:Admin:publishers }

logout:
    path:     /logout
