# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    api.book.service:
        class: ApiBundle\Service\BookService
        public: true
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
